name: GitHub CI
on: 
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows64_build:
    name: Windows x86_64 Build
    runs-on: self-hosted
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-libevent mingw-w64-x86_64-pcre2 patch
        msystem: MINGW64
        path-type: inherit
    - name: Build
      run: bash scripts/build.windows.release.sh
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: subconverter_win64
        path: subconverter/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: 7z a subconverter_win64.7z subconverter/
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: subconverter_win64.7z
        draft: true

  windows32_build:
    name: Windows x86 Build
    runs-on: self-hosted
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel git mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-libevent mingw-w64-i686-pcre2 patch
        msystem: MINGW32
        path-type: inherit
    - name: Build
      run: bash scripts/build.windows.release.sh
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: subconverter_win32
        path: subconverter/
    - name: Package Release
      if: startsWith(github.ref, 'refs/tags/')
      run: 7z a subconverter_win32.7z subconverter/
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: subconverter_win32.7z
        draft: true
